/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/jobs/wrangler.jsonc --include-runtime=false --env-interface=JobsEnv workers/jobs/worker-configuration.d.ts` (hash: 74d7d5a44258f3bbf37d90652f80b476)
interface __BaseEnv_JobsEnv {
	BUCKET: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	CLAUDE_MODEL: "claude-sonnet-4-6";
	CLAUDE_REPORT_MODEL: "claude-sonnet-4-6";
	GEMINI_TTS_MODEL: "gemini-2.5-flash-preview-tts";
	GEMINI_IMAGE_MODEL: "gemini-2.5-flash-image";
	VIDEO_SLIDE_CONCURRENCY: "3";
	ANTHROPIC_API_KEY: string;
	VOYAGE_API_KEY: string;
	GEMINI_API_KEY: string;
	VIDEO_RENDERER: DurableObjectNamespace<import("./src/index").VideoRenderer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "VideoRenderer";
	}
	interface Env extends __BaseEnv_JobsEnv {}
}
interface JobsEnv extends __BaseEnv_JobsEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLAUDE_MODEL" | "CLAUDE_REPORT_MODEL" | "GEMINI_TTS_MODEL" | "GEMINI_IMAGE_MODEL" | "VIDEO_SLIDE_CONCURRENCY" | "ANTHROPIC_API_KEY" | "VOYAGE_API_KEY" | "GEMINI_API_KEY">> {}
}
