/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/jobs/wrangler.jsonc --include-runtime=false --env-interface=JobsEnv workers/jobs/worker-configuration.d.ts` (hash: d0e220c42b083f01c05db6aaa8df3ffe)
interface __BaseEnv_JobsEnv {
	BUCKET: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	AI: Ai;
	GEMINI_REPORT_MODEL: "gemini-3.8-flash";
	GEMINI_FALLBACK_MODEL: "gemini-3.5-flash-lite";
	GEMINI_EMBEDDING_MODEL: "gemini-embedding-2";
	GEMINI_TTS_MODEL: "gemini-3.8-flash-tts";
	GEMINI_TTS_FALLBACK_MODEL: "gemini-3.8-flash-lite-tts";
	IMAGE_MODEL: "@cf/black-forest-labs/flux-2-klein-4b";
	IMAGE_DAILY_LIMIT: "100";
	VIDEO_SLIDE_CONCURRENCY: "3";
	DEMO_EMAIL_DOMAIN: "demo.notebooklm.invalid";
	GEMINI_API_KEY: string;
	VIDEO_RENDERER: DurableObjectNamespace<import("./src/index").VideoRenderer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "VideoRenderer";
	}
	interface Env extends __BaseEnv_JobsEnv {}
}
interface JobsEnv extends __BaseEnv_JobsEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_REPORT_MODEL" | "GEMINI_FALLBACK_MODEL" | "GEMINI_EMBEDDING_MODEL" | "GEMINI_TTS_MODEL" | "GEMINI_TTS_FALLBACK_MODEL" | "IMAGE_MODEL" | "IMAGE_DAILY_LIMIT" | "VIDEO_SLIDE_CONCURRENCY" | "DEMO_EMAIL_DOMAIN" | "GEMINI_API_KEY">> {}
}
